-- Minimumstruktur for å støtte vedtakfakta-testene.
-- VEDTAK 1234 og 4321 må finnes for at VEDTAKFAKTA-radene i V1_14 skal kunne settes inn (FK).
insert into PERSON(PERSON_ID, FODSELSNR, ETTERNAVN, FORNAVN)
values (1, '123', 'Bestesen', 'Test');

Insert into SAK (SAK_ID, SAKSKODE, REG_DATO, REG_USER, MOD_DATO, MOD_USER, TABELLNAVNALIAS, OBJEKT_ID, AAR, LOPENRSAK,
                 DATO_AVSLUTTET, SAKSTATUSKODE, ARKIVNOKKEL, AETATENHET_ARKIV, ARKIVHENVISNING, BRUKERID_ANSVARLIG,
                 AETATENHET_ANSVARLIG, OBJEKT_KODE, STATUS_ENDRET, PARTISJON, ER_UTLAND)
values ('1', 'AA', DATE '2022-02-01', 'IMB0826', DATE '2025-02-22',
        'MM0826', 'PERS', '1', '2021', '1', null, 'AKTIV', null, null, null, 'IMB0826', '0826', 1,
        DATE '2025-02-22', null, 'N');

insert into VEDTAK (VEDTAK_ID, SAK_ID, VEDTAKSTATUSKODE, VEDTAKTYPEKODE, UTFALLKODE, RETTIGHETKODE, PERSON_ID, FRA_DATO,
                    TIL_DATO, AETATENHET_BEHANDLER, LOPENRSAK, AAR, LOPENRVEDTAK, AKTFASEKODE, DATO_MOTTATT)
values ('1234', 1, 'IVERK', 'O', 'JA', 'AAP', '1', DATE '2022-08-30',
        DATE '2023-08-30', '4402', 1, '2021', 1, 'IKKE', DATE '2022-08-30');

insert into VEDTAK (VEDTAK_ID, SAK_ID, VEDTAKSTATUSKODE, VEDTAKTYPEKODE, UTFALLKODE, RETTIGHETKODE, PERSON_ID, FRA_DATO,
                    TIL_DATO, AETATENHET_BEHANDLER, LOPENRSAK, AAR, LOPENRVEDTAK, AKTFASEKODE, DATO_MOTTATT)
values ('4321', 1, 'IVERK', 'O', 'JA', 'AAP', '1', DATE '2022-08-30',
        DATE '2023-08-30', '4402', 1, '2021', 2, 'IKKE', DATE '2022-08-30');


-- Vedtakfakta for unntak fra maksimal stønadsperiode AAP, brukt for å teste
-- ArenaVedtakfakta.somBooleanVerdi() og somDatoVerdi().
-- UNNTAKAAP har Arena-verdiene 'J'/'N', AAPVILKUNN er en dato på formatet dd-MM-yyyy.
insert into VEDTAKFAKTA (VEDTAK_ID, VEDTAKFAKTAKODE, VEDTAKVERDI, REG_DATO)
values (1234, 'UNNTAKAAP', 'J', DATE '2025-03-28');

insert into VEDTAKFAKTA (VEDTAK_ID, VEDTAKFAKTAKODE, VEDTAKVERDI, REG_DATO)
values (1234, 'AAPVILKUNN', '01-02-2025', DATE '2025-03-28');

insert into VEDTAKFAKTA (VEDTAK_ID, VEDTAKFAKTAKODE, VEDTAKVERDI, REG_DATO)
values (4321, 'UNNTAKAAP', 'N', DATE '2025-03-28');
