apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: arenaoppslag
  namespace: aap
  labels:
    team: aap
    komponent: datadeling
spec:
  image: {{image}}
  azure:
    application:
      enabled: true
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  terminationGracePeriodSeconds: 30
  liveness:
    path: /actuator/live
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  readiness:
    path: /actuator/ready
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  prometheus:
    enabled: true
    path: /actuator/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: api
          cluster: {{cluster}}-gcp
          namespace: aap
        - application: api-intern
          cluster: {{cluster}}-gcp
          namespace: aap
  webproxy: true
  ingresses:
    - {{ingress}}
  vault:
    enabled: true
    paths:
      - kvPath: {{ vault_db_config_path }}
        mountPath: /secrets/dbconfig
      - kvPath: {{ vault_db_creds_path }}
        mountPath: /secrets/dbcreds
  env:
    - name: DB_USERNAME_PATH
      value: "/secrets/dbcreds/username"
    - name: DB_PASSWORD_PATH
      value: "/secrets/dbcreds/password"
    - name: DB_JDBC_URL_PATH
      value: "/secrets/dbconfig/jdbc_url"