db:
  host: a01dbfl048.adeo.no
  port: 1521
  database: areq02
env: dev
ingress: https://arenaoppslag.dev-fss-pub.nais.io
vault_db_config_path: oracle/data/dev/config/arena_q2
vault_db_creds_path: oracle/data/dev/creds/arena_q2-arena_tilgang_aap