Insert into BERERGNINGSLEDD(VERDI,PERSON_ID,BEREGNINGSLEDDKODE) values (5280,1,'AAP');
Insert into BERERGNINGSLEDD(VERDI,PERSON_ID,BEREGNINGSLEDDKODE) values (15060,2,'AAP');
Insert into BERERGNINGSLEDD(VERDI,PERSON_ID,BEREGNINGSLEDDKODE) values (10580,3,'AAP');
Insert into BERERGNINGSLEDD(VERDI,PERSON_ID,BEREGNINGSLEDDKODE) values (10320,4,'AAP');
Insert into BERERGNINGSLEDD(VERDI,PERSON_ID,BEREGNINGSLEDDKODE) values (11120,5,'AAP');
Insert into BERERGNINGSLEDD(VERDI,PERSON_ID,BEREGNINGSLEDDKODE) values (0,6,'AAP');
Insert into BERERGNINGSLEDD(VERDI,PERSON_ID,BEREGNINGSLEDDKODE) values (5160,7,'AAP');
Insert into BERERGNINGSLEDD(VERDI,PERSON_ID,BEREGNINGSLEDDKODE) values (7460,8,'AAP');

Insert into BEREGNINGSLEDD (VERDI,PERSON_ID,BEREGNINGSLEDDKODE) values (460,1,'MAAPU');
Insert into BEREGNINGSLEDD (VERDI,PERSON_ID,BEREGNINGSLEDDKODE) values (0,2,'MAAPU');
Insert into BEREGNINGSLEDD (VERDI,PERSON_ID,BEREGNINGSLEDDKODE) values (10460,3,'MAAPU');
Insert into BEREGNINGSLEDD (VERDI,PERSON_ID,BEREGNINGSLEDDKODE) values (10460,4,'MAAPU');
Insert into BEREGNINGSLEDD (VERDI,PERSON_ID,BEREGNINGSLEDDKODE) values (5,5,'MAAPU');
Insert into BEREGNINGSLEDD (VERDI,PERSON_ID,BEREGNINGSLEDDKODE) values (10460,6,'MAAPU');
Insert into BEREGNINGSLEDD (VERDI,PERSON_ID,BEREGNINGSLEDDKODE) values (10000,7,'MAAPU');
Insert into BEREGNINGSLEDD (VERDI,PERSON_ID,BEREGNINGSLEDDKODE) values (10460,8,'MAAPU');
