database:
  url: jdbc:oracle:thin:@${DB_HOST}:${DB_PORT}/${DB_DATABASE}
  username: ${ARENA_DB_USERNAME}
  password: ${ARENA_DB_PASSWORD}
tokenx:
  jwksUri: ${TOKEN_X_JWKS_URI}
  issuer: ${TOKEN_X_ISSUER}
  clientId: ${TOKEN_X_CLIENT_ID}