database:
  url: jdbc:oracle:thin:@${DB_HOST}:${DB_PORT}/${DB_DATABASE}
  username: ${ARENA_DB_USERNAME}
  password: ${ARENA_DB_PASSWORD}
azure:
  jwksUri: ${AZURE_OPENID_CONFIG_JWKS_URI}
  issuer: ${AZURE_OPENID_CONFIG_ISSUER}
  clientId: ${AZURE_APP_CLIENT_ID}