-- En kopi av viewene som ligger i Arena, for å kunne teste logikk i unittester. Skal ikke brukes til noe produksjon.
CREATE TABLE AKTIVITETFASE
(
    AKTFASEKODE VARCHAR2(10) NOT NULL,
    AKTFASENAVN VARCHAR2(35) NOT NULL,
    DATO_FRA    DATE         NOT NULL,
    DATO_TIL    DATE         NOT NULL,
    REG_DATO    DATE,
    MOD_DATO    DATE,
    REG_USER    VARCHAR2(8),
    MOD_USER    VARCHAR2(8),
    CONSTRAINT PK_AKTIVITETFASE PRIMARY KEY (AKTFASEKODE)
);
CREATE TABLE ANMERKNING
(
    ANMERKNINGKODE  VARCHAR2(5)  NOT NULL,
    REG_USER        VARCHAR2(8),
    REG_DATO        DATE,
    VERDI           NUMBER(5, 0),
    ANMERKNING_ID   NUMBER       NOT NULL,
    TABELLNAVNALIAS VARCHAR2(10) NOT NULL,
    OBJEKT_ID       NUMBER       NOT NULL,
    VEDTAK_ID       NUMBER,
    PARTISJON       NUMBER(8, 0),
    MOD_USER        VARCHAR2(8),
    MOD_DATO        DATE,
    VERDI2          NUMBER(5, 0),
    CONSTRAINT PK_ANMERKNING PRIMARY KEY (ANMERKNING_ID)
);
CREATE TABLE ANMERKNINGTYPE
(
    ANMERKNINGKODE   VARCHAR2(5)   NOT NULL,
    ANMERKNINGNAVN   VARCHAR2(100) NOT NULL,
    BESKRIVELSE      VARCHAR2(255),
    HENDELSETYPEKODE VARCHAR2(7)   NOT NULL,
    CONSTRAINT PK_ANMERKNINGTYPE PRIMARY KEY (ANMERKNINGKODE)

);
CREATE TABLE BEREGNINGSLOGG
(
    PERSON_ID       NUMBER        NOT NULL,
    VEDTAK_ID       NUMBER        NOT NULL,
    TABELLNAVNALIAS VARCHAR2(10)  NOT NULL,
    OBJEKT_ID       NUMBER(10, 0) NOT NULL,
    DATO_FRA        DATE          NOT NULL,
    DATO_TIL        DATE          NOT NULL,
    REG_USER        VARCHAR2(8),
    REG_DATO        DATE,
    KOMMENTAR       VARCHAR2(30),
    PARTISJON       NUMBER(8, 0),
    CONSTRAINT PK_BEREGNINGSLOGG PRIMARY KEY (PERSON_ID, VEDTAK_ID)

);
CREATE TABLE BREV_TEKSTVARIANT
(
    TEKSTVARIANTKODE VARCHAR2(20)  NOT NULL,
    TEKSTVARIANTNAVN VARCHAR2(255) NOT NULL,
    REG_USER         VARCHAR2(8),
    REG_DATO         DATE,
    MOD_USER         VARCHAR2(8),
    MOD_DATO         DATE,
    CONSTRAINT PK_BREV_TEKSTVARIANT PRIMARY KEY (TEKSTVARIANTKODE)
);
CREATE TABLE MELDEKORT
(
    MELDEKORT_ID                NUMBER       NOT NULL,
    PERSON_ID                   NUMBER       NOT NULL,
    DATO_INNKOMMET              DATE,
    DATO_UTSENDT                DATE,
    MKSREFERANSE                VARCHAR2(21),
    MELDEKORTKODE               VARCHAR2(5),
    MKSKORTKODE                 VARCHAR2(2)  NOT NULL,
    STATUS_ARBEIDET             VARCHAR2(1),
    STATUS_FERIE                VARCHAR2(1),
    STATUS_KURS                 VARCHAR2(1),
    STATUS_NYTT_MELDEKORT       VARCHAR2(1),
    STATUS_SYK                  VARCHAR2(1),
    STATUS_PERIODESPOERSMAAL    VARCHAR2(1),
    STATUS_SOEKER_DAGPENGER     VARCHAR2(1),
    STATUS_ANNETFRAVAER_ATTF    VARCHAR2(1),
    STATUS_ATTFORINGSBISTAND    VARCHAR2(1),
    STATUS_ATTFORINGSTILTAK     VARCHAR2(1),
    REG_DATO                    DATE,
    REG_USER                    VARCHAR2(8),
    MOD_DATO                    DATE,
    MOD_USER                    VARCHAR2(8),
    AAR                         NUMBER(4, 0) NOT NULL,
    PERIODEKODE                 VARCHAR2(2)  NOT NULL,
    BEREGNINGSTATUSKODE         VARCHAR2(5)  NOT NULL,
    STATUS_ANNETFRAVAER         VARCHAR2(1),
    STATUS_FORTSATT_ARBEIDSOKER VARCHAR2(1),
    FEIL_PAA_KORT               VARCHAR2(1),
    VEILEDNING                  VARCHAR2(1),
    KOMMENTAR                   VARCHAR2(255),
    MELDEGRUPPEKODE             VARCHAR2(5),
    RETURBREVKODE               VARCHAR2(2),
    AB_POSTKODE                 VARCHAR2(1),
    MELDEKORT_ID_RELATERT       NUMBER,
    PARTISJON                   NUMBER(8, 0),
    CONSTRAINT PK_MELDEKORT PRIMARY KEY (MELDEKORT_ID)
);
CREATE TABLE MELDEKORTDAG
(
    MELDEKORT_ID             NUMBER       NOT NULL,
    UKENR                    NUMBER(2, 0) NOT NULL,
    DAGNR                    NUMBER(1, 0) NOT NULL,
    STATUS_ARBEIDSDAG        VARCHAR2(1)  NOT NULL,
    STATUS_FERIE             VARCHAR2(1),
    STATUS_KURS              VARCHAR2(1)  NOT NULL,
    STATUS_SYK               VARCHAR2(1)  NOT NULL,
    STATUS_ANNETFRAVAER_ATTF VARCHAR2(1),
    TIMER_ARBEIDET           NUMBER(3, 1) NOT NULL,
    TIMER_ARB_MENS_PERM      NUMBER(3, 1),
    REG_USER                 VARCHAR2(8),
    REG_DATO                 DATE,
    MOD_USER                 VARCHAR2(8),
    MOD_DATO                 DATE,
    STATUS_ANNETFRAVAER      VARCHAR2(1),
    MELDEGRUPPEKODE          VARCHAR2(5),
    PARTISJON                NUMBER(8, 0)
);
CREATE TABLE MELDEKORTPERIODE
(
    AAR         NUMBER(4, 0) NOT NULL,
    PERIODEKODE VARCHAR2(2)  NOT NULL,
    UKENR_UKE1  NUMBER(2, 0) NOT NULL,
    UKENR_UKE2  NUMBER(2, 0) NOT NULL,
    DATO_FRA    DATE         NOT NULL,
    DATO_TIL    DATE         NOT NULL
);
CREATE TABLE PERSON
(
    PERSON_ID                     NUMBER NOT NULL,
    FODSELSDATO                   DATE,
    STATUS_DNR                    VARCHAR2(1),
    PERSONNR                      NUMBER(5, 0),
    FODSELSNR                     VARCHAR2(11),
    ETTERNAVN                     VARCHAR2(30),
    FORNAVN                       VARCHAR2(30),
    DATO_FRA                      DATE,
    STATUS_SAMTYKKE               VARCHAR2(1),
    DATO_SAMTYKKE                 DATE,
    VERNEPLIKTKODE                VARCHAR2(5),
    MAALFORM                      VARCHAR2(2),
    LANDKODE_STATSBORGER          VARCHAR2(2),
    KONTONUMMER                   VARCHAR2(11),
    STATUS_BILDISP                VARCHAR2(1),
    FORMIDLINGSGRUPPEKODE         VARCHAR2(5),
    VIKARGRUPPEKODE               VARCHAR2(5),
    KVALIFISERINGSGRUPPEKODE      VARCHAR2(5),
    RETTIGHETSGRUPPEKODE          VARCHAR2(5),
    REG_DATO                      DATE,
    REG_USER                      VARCHAR2(8),
    MOD_DATO                      DATE,
    MOD_USER                      VARCHAR2(8),
    AETATORGENHET                 VARCHAR2(8),
    LONNSLIPP_EPOST               VARCHAR2(1),
    DATO_OVERFORT_AMELDING        DATE,
    DATO_SIST_INAKTIV             DATE,
    BEGRUNNELSE_FORMIDLINGSGRUPPE VARCHAR2(2000),
    HOVEDMAALKODE                 VARCHAR2(10),
    BRUKERID_NAV_KONTAKT          VARCHAR2(8),
    FR_KODE                       VARCHAR2(2),
    ER_DOED                       VARCHAR2(1),
    PERSON_ID_STATUS              VARCHAR2(20),
    SPERRET_KOMMENTAR             VARCHAR2(500),
    SPERRET_TIL                   DATE,
    SPERRET_DATO                  DATE,
    SPERRET_AV                    VARCHAR2(8),
    CONSTRAINT PK_PERSON PRIMARY KEY (PERSON_ID)
);
CREATE TABLE POSTERING
(
    POSTERING_ID                NUMBER        NOT NULL,
    BELOP                       NUMBER(12, 2) NOT NULL,
    BELOPKODE                   VARCHAR2(5)   NOT NULL,
    DATO_PERIODE_FRA            DATE          NOT NULL,
    DATO_PERIODE_TIL            DATE          NOT NULL,
    DATO_POSTERT                DATE          NOT NULL,
    EKSTERNENHET_ID_ALTMOTTAKER NUMBER,
    AAR                         NUMBER(4, 0)  NOT NULL,
    PERSON_ID                   NUMBER        NOT NULL,
    POSTERINGSATS               NUMBER(8, 2),
    POSTERINGTYPEKODE           VARCHAR2(5)   NOT NULL,
    TRANSAKSJONSKODE            VARCHAR2(5)   NOT NULL,
    ANTALL                      NUMBER(14, 4),
    MELDINGKODE                 VARCHAR2(10),
    REG_DATO                    DATE,
    REG_USER                    VARCHAR2(8),
    MOD_DATO                    DATE,
    MOD_USER                    VARCHAR2(8),
    DATO_GRUNNLAG               DATE          NOT NULL,
    VEDTAK_ID                   NUMBER        NOT NULL,
    ARTKODE                     VARCHAR2(5)   NOT NULL,
    PROSJEKTNUMMER              VARCHAR2(4),
    KAPITTEL                    VARCHAR2(4)   NOT NULL,
    POST                        VARCHAR2(2)   NOT NULL,
    UNDERPOST                   VARCHAR2(3)   NOT NULL,
    KONTOSTEDKODE               VARCHAR2(5),
    MELDEKORT_ID                NUMBER,
    TRANSAKSJONSTEKST           VARCHAR2(60),
    BRUKER_ID_SAKSBEHANDLER     VARCHAR2(8)   NOT NULL,
    AETATENHET_ANSVARLIG        VARCHAR2(8)   NOT NULL,
    TABELLNAVNALIAS_KILDE       VARCHAR2(10),
    OBJEKT_ID_KILDE             NUMBER(20, 0),
    PARTISJON                   NUMBER(8, 0),
    CONSTRAINT PK_POSTERING PRIMARY KEY (POSTERING_ID)
);
CREATE TABLE RETTIGHETTYPE
(
    RETTIGHETKODE             VARCHAR2(10) NOT NULL,
    RETTIGHETNAVN             VARCHAR2(60) NOT NULL,
    DATO_GYLDIG_FRA           DATE         NOT NULL,
    DATO_GYLDIG_TIL           DATE,
    REG_DATO                  DATE,
    REG_USER                  VARCHAR2(8),
    MOD_DATO                  DATE,
    MOD_USER                  VARCHAR2(8),
    SAKSKODE                  VARCHAR2(10) NOT NULL,
    RETTIGHETSKLASSEKODE      VARCHAR2(5),
    BELOPKODE                 VARCHAR2(5),
    RANGNR                    NUMBER(3, 0),
    TRANSAKSJONSKODE          VARCHAR2(5),
    STATUS_KONTERBAR          VARCHAR2(1)  NOT NULL,
    TRANSAKSJONSKODE_FORSKUDD VARCHAR2(5),
    RETTIGHETNAVN_KORT        VARCHAR2(20),
    FORSKUDD_BETPLAN          VARCHAR2(1),
    SATSVALG                  VARCHAR2(10),
    STATUS_TILTAK             VARCHAR2(1),
    STATUS_START_VEDTAK       VARCHAR2(1),
    BILAG_KREVES_JN           VARCHAR2(1),
    BETPLAN_JN                VARCHAR2(1)  NOT NULL,
    GJELDERKODE               VARCHAR2(10),
    CONSTRAINT PK_RETTIGHETTYPE PRIMARY KEY (RETTIGHETKODE)
);
CREATE TABLE SAK
(
    SAK_ID               NUMBER,
    SAKSKODE             VARCHAR2(10),
    REG_DATO             DATE,
    REG_USER             VARCHAR2(8),
    MOD_DATO             DATE,
    MOD_USER             VARCHAR2(8),
    TABELLNAVNALIAS      VARCHAR2(10),
    OBJEKT_ID            NUMBER,
    AAR                  NUMBER(4, 0),
    LOPENRSAK            NUMBER(7, 0),
    DATO_AVSLUTTET       DATE,
    SAKSTATUSKODE        VARCHAR2(5),
    ARKIVNOKKEL          VARCHAR2(7),
    AETATENHET_ARKIV     VARCHAR2(8),
    ARKIVHENVISNING      VARCHAR2(255),
    BRUKERID_ANSVARLIG   VARCHAR2(8),
    AETATENHET_ANSVARLIG VARCHAR2(8),
    OBJEKT_KODE          VARCHAR2(10),
    STATUS_ENDRET        DATE,
    PARTISJON            NUMBER(8, 0),
    ER_UTLAND            VARCHAR2(1),
    CONSTRAINT PK_SAK PRIMARY KEY (SAK_ID)
);
CREATE TABLE SAKSRELASJON
(
    SAKSRELASJON_ID       NUMBER,
    RELASJONSKODE         VARCHAR2(5),
    SAK_ID                NUMBER,
    EKSTERNENHET_ID       NUMBER,
    EKSTERNSAKBETEGNELSE  VARCHAR2(30),
    SAK_ID_INTERNRELATERT NUMBER,
    REG_DATO              DATE,
    REG_USER              VARCHAR2(8),
    MOD_DATO              DATE,
    MOD_USER              VARCHAR2(8),
    PARTISJON             NUMBER(8, 0),
    CONSTRAINT PK_SAKSRELASJON PRIMARY KEY (SAKSRELASJON_ID)
);
CREATE TABLE SAKSTATUS
(
    SAKSTATUSKODE VARCHAR2(5)  NOT NULL,
    SAKSTATUSNAVN VARCHAR2(30) NOT NULL,
    FLYTTES_JN    VARCHAR2(1)  NOT NULL,
    CONSTRAINT PK_SAKSTATUS PRIMARY KEY (SAKSTATUSKODE)

);
CREATE TABLE SAKSTYPE
(
    SAKSKODE              VARCHAR2(10) NOT NULL,
    SAKSTYPENAVN          VARCHAR2(30) NOT NULL,
    ARKIVNOKKEL           VARCHAR2(10),
    LUKKES_JN             VARCHAR2(1)  NOT NULL,
    ANT_DAGER_FOER_LUKK   NUMBER(5, 0),
    HISTORISERES_JN       VARCHAR2(1)  NOT NULL,
    ANT_DAGER_FOER_HIST   NUMBER(5, 0),
    FLYTTES_JN            VARCHAR2(1)  NOT NULL,
    SPESIAL_FLYTTES_JN    VARCHAR2(1)  NOT NULL,
    LOGG_FLYTT_OPPGAVE_JN VARCHAR2(1)  NOT NULL,
    KORTNAVN              VARCHAR2(10),
    TEMASAK_JN            VARCHAR2(1)  NOT NULL,
    TEMANAVN              VARCHAR2(30),
    EKSTERN_JN            VARCHAR2(1)  NOT NULL,
    FEILUTBETALING_JN     VARCHAR2(1)  NOT NULL,
    OPPRETT_MANUELT_JN    VARCHAR2(1)  NOT NULL,
    DATO_GYLDIG_FRA       DATE         NOT NULL,
    DATO_GYLDIG_TIL       DATE,
    PROSESSGRUPPE         VARCHAR2(50),
    KLAGE_SENDES          VARCHAR2(100),
    GJELDERKODE           VARCHAR2(10),
    BRUK_FULLMEKTIG_BREV  VARCHAR2(1)  NOT NULL,
    CONSTRAINT PK_SAKSTYPE PRIMARY KEY (SAKSKODE)
);
CREATE TABLE SIM_UTBETALINGSGRUNNLAG
(
    SIM_POSTERING_ID            NUMBER(20, 0) NOT NULL,
    BELOP                       NUMBER(12, 2),
    BELOPKODE                   VARCHAR2(5)   NOT NULL,
    EKSTERNENHET_ID_ALTMOTTAKER NUMBER(20, 0),
    AAR                         NUMBER(4, 0)  NOT NULL,
    DATO_PERIODE_FRA            DATE          NOT NULL,
    PERSON_ID                   NUMBER(20, 0) NOT NULL,
    POSTERINGTYPEKODE           VARCHAR2(5),
    TRANSAKSJONSKODE            VARCHAR2(5)   NOT NULL,
    ANTALL                      NUMBER(14, 4),
    POSTERINGSATS               NUMBER(8, 2),
    MELDINGKODE                 VARCHAR2(10),
    ARTKODE                     VARCHAR2(5)   NOT NULL,
    DATO_PERIODE_TIL            DATE          NOT NULL,
    REG_DATO                    DATE,
    KAPITTEL                    VARCHAR2(4),
    MOD_DATO                    DATE,
    REG_USER                    VARCHAR2(8),
    MOD_USER                    VARCHAR2(8),
    VEDTAK_ID                   NUMBER(20, 0),
    DATO_GRUNNLAG               DATE          NOT NULL,
    POST                        VARCHAR2(2),
    PROSJEKTNUMMER              VARCHAR2(4),
    SIM_MELDEKORT_ID            NUMBER(20, 0),
    TRANSAKSJONSTEKST           VARCHAR2(60),
    UNDERPOST                   VARCHAR2(3),
    KONTOSTEDKODE               VARCHAR2(5)   NOT NULL,
    STATUS_MANUELL              VARCHAR2(1),
    KOMMENTAR                   VARCHAR2(2000),
    VEDTAK_ID_FEILUTBET         NUMBER        NOT NULL,
    TABELLNAVNALIAS_KILDE       VARCHAR2(10),
    OBJEKT_ID_KILDE             NUMBER(20, 0),
    PARTISJON                   NUMBER(8, 0),
    BELOP_SATT_MANUELT          VARCHAR2(1),
    POSTERING_ID                NUMBER,
    CONSTRAINT PK_SIM_UTBETALINGSGRUNNLAG PRIMARY KEY (SIM_POSTERING_ID)
);
CREATE TABLE SPESIALUTBETALING
(
    SPESUTBETALING_ID           NUMBER       NOT NULL,
    PERSON_ID                   NUMBER       NOT NULL,
    VEDTAK_ID                   NUMBER,
    LOPENR                      NUMBER(3, 0),
    BRUKER_ID_SAKSBEHANDLER     VARCHAR2(8)  NOT NULL,
    BRUKER_ID_BESLUTTER         VARCHAR2(8),
    DATO_UTBETALING             DATE,
    BEGRUNNELSE                 VARCHAR2(2000),
    BELOP                       NUMBER(12, 2),
    BELOPKODE                   VARCHAR2(5)  NOT NULL,
    RETTIGHETKODE               VARCHAR2(10) NOT NULL,
    AKTFASEKODE                 VARCHAR2(10) NOT NULL,
    VEDTAKSTATUSKODE            VARCHAR2(5)  NOT NULL,
    POSTERINGTYPEKODE           VARCHAR2(5)  NOT NULL,
    REFERANSE_TOTAL             VARCHAR2(255),
    DATO_FRA                    DATE,
    DATO_TIL                    DATE,
    REG_DATO                    DATE,
    REG_USER                    VARCHAR2(8),
    MOD_DATO                    DATE,
    MOD_USER                    VARCHAR2(8),
    EKSTERNENHET_ID_ALTMOTTAKER NUMBER,
    FERIEGRUNNLAG               NUMBER(12, 2),
    FERIEGRUNNLAGKODE           VARCHAR2(10),
    ORDINAER_YTELSE             VARCHAR2(1),
    REFERANSE_BILAG             VARCHAR2(25),
    STATUS_BILAG                VARCHAR2(1),
    STATUS_ANVIS_BILAG          VARCHAR2(1),
    PARTISJON                   NUMBER(8, 0),
    VALGT_UTBET_TYPE            VARCHAR2(20),
    KATEGORI                    VARCHAR2(50),
    CONSTRAINT PK_SPESIALUTBETALING PRIMARY KEY (SPESUTBETALING_ID)
);
CREATE TABLE UTFALLTYPE
(
    UTFALLKODE  VARCHAR2(10)  NOT NULL,
    UTFALLNAVN  VARCHAR2(30)  NOT NULL,
    UTFALLTEKST VARCHAR2(255) NOT NULL,
    CONSTRAINT PK_UTFALLTYPE PRIMARY KEY (UTFALLKODE)
);
CREATE TABLE VEDTAK
(
    VEDTAK_ID              NUMBER NOT NULL,
    SAK_ID                 NUMBER,
    VEDTAKSTATUSKODE       VARCHAR2(5),
    VEDTAKTYPEKODE         VARCHAR2(10),
    REG_DATO               DATE,
    REG_USER               VARCHAR2(8),
    MOD_DATO               DATE,
    MOD_USER               VARCHAR2(8),
    UTFALLKODE             VARCHAR2(10),
    BEGRUNNELSE            VARCHAR2(4000),
    BRUKERID_ANSVARLIG     VARCHAR2(8),
    AETATENHET_BEHANDLER   VARCHAR2(8),
    AAR                    NUMBER(4, 0),
    LOPENRSAK              NUMBER(7, 0),
    LOPENRVEDTAK           NUMBER(3, 0),
    RETTIGHETKODE          VARCHAR2(10),
    AKTFASEKODE            VARCHAR2(10),
    BREV_ID                NUMBER,
    TOTALBELOP             NUMBER(8, 2),
    DATO_MOTTATT           DATE,
    VEDTAK_ID_RELATERT     NUMBER,
    AVSNITTLISTEKODE_VALGT VARCHAR2(20),
    PERSON_ID              NUMBER,
    BRUKERID_BESLUTTER     VARCHAR2(8),
    STATUS_SENSITIV        VARCHAR2(1),
    VEDLEGG_BETPLAN        VARCHAR2(1),
    PARTISJON              NUMBER(8, 0),
    OPPSUMMERING_SB2       VARCHAR2(4000),
    DATO_UTFORT_DEL1       DATE,
    DATO_UTFORT_DEL2       DATE,
    OVERFORT_NAVI          VARCHAR2(1),
    FRA_DATO               DATE,
    TIL_DATO               DATE,
    SF_OPPFOLGING_ID       NUMBER,
    STATUS_SOSIALDATA      VARCHAR2(1),
    KONTOR_SOSIALDATA      VARCHAR2(8),
    TEKSTVARIANTKODE       VARCHAR2(20),
    VALGT_BESLUTTER        VARCHAR2(8),
    TEKNISK_VEDTAK         VARCHAR2(1),
    DATO_INNSTILT          DATE,
    ER_UTLAND              VARCHAR2(1),
    CONSTRAINT PK_VEDTAK PRIMARY KEY (VEDTAK_ID)
);
CREATE TABLE VEDTAKFAKTA
(
    VEDTAK_ID       NUMBER,
    VEDTAKFAKTAKODE VARCHAR2(10),
    VEDTAKVERDI     VARCHAR2(2000),
    REG_DATO        DATE,
    REG_USER        VARCHAR2(8),
    MOD_DATO        DATE,
    MOD_USER        VARCHAR2(8),
    PERSON_ID       NUMBER,
    PARTISJON       NUMBER(8, 0),
    CONSTRAINT PK_VEDTAKFAKTA PRIMARY KEY (VEDTAK_ID)
);
CREATE TABLE VEDTAKFAKTATYPE
(
    VEDTAKFAKTAKODE      VARCHAR2(10)  NOT NULL,
    SKJERMBILDETEKST     VARCHAR2(255) NOT NULL,
    STATUS_KVOTEBRUK     VARCHAR2(1)   NOT NULL,
    STATUS_OVERSIKT      VARCHAR2(1)   NOT NULL,
    VEDTAKFAKTANAVN      VARCHAR2(30)  NOT NULL,
    BESKRIVELSE          VARCHAR2(255),
    ORACLETYPE           VARCHAR2(10),
    FELTLENGDE           NUMBER(3, 0),
    AVSNITT_ID_LEDETEKST NUMBER,
    REG_DATO             DATE,
    REG_USER             VARCHAR2(8),
    MOD_DATO             DATE,
    MOD_USER             VARCHAR2(8),
    CONSTRAINT PK_VEDTAKFAKTATYPE PRIMARY KEY (VEDTAKFAKTAKODE)
);
CREATE TABLE VEDTAKSTATUS
(
    VEDTAKSTATUSKODE VARCHAR2(5)  NOT NULL,
    VEDTAKSTATUSNAVN VARCHAR2(30) NOT NULL,
    BESKRIVELSE      VARCHAR2(255),
    CONSTRAINT PK_VEDTAKSTATUS PRIMARY KEY (VEDTAKSTATUSKODE)
);
CREATE TABLE VEDTAKTYPE
(
    VEDTAKTYPEKODE           VARCHAR2(10) NOT NULL,
    VEDTAKTYPENAVN           VARCHAR2(30) NOT NULL,
    BESKRIVELSE              VARCHAR2(255),
    DATO_FRA                 DATE         NOT NULL,
    DATO_TIL                 DATE         NOT NULL,
    REG_USER                 VARCHAR2(8),
    REG_DATO                 DATE,
    MOD_USER                 VARCHAR2(8),
    MOD_DATO                 DATE,
    AVSNITTLISTEKODE_VALGFRI VARCHAR2(20),
    CONSTRAINT PK_VEDTAKTYPE PRIMARY KEY (VEDTAKTYPEKODE)
);

INSERT INTO PERSON(PERSON_ID, FODSELSNR)
VALUES (4873545, '1');

Insert into SAK (SAK_ID, SAKSKODE, REG_DATO, REG_USER, MOD_DATO, MOD_USER, TABELLNAVNALIAS, OBJEKT_ID, AAR, LOPENRSAK,
                 DATO_AVSLUTTET, SAKSTATUSKODE, ARKIVNOKKEL, AETATENHET_ARKIV, ARKIVHENVISNING, BRUKERID_ANSVARLIG,
                 AETATENHET_ANSVARLIG, OBJEKT_KODE, STATUS_ENDRET, PARTISJON, ER_UTLAND)
values ('13489616', 'INDIV', to_date('02.02.2022', 'DD.MM.RRRR'), 'IMB0826', to_date('22.02.2023', 'DD.MM.RRRR'),
        'MM0826', 'PERS', '4873545', '2021', '285758', null, 'INAKT', null, null, null, 'IMB0826', '0826', null,
        to_date('22.02.2023', 'DD.MM.RRRR'), null, 'N');


Insert into VEDTAK (VEDTAK_ID, SAK_ID, VEDTAKSTATUSKODE, VEDTAKTYPEKODE, REG_DATO, REG_USER, MOD_DATO, MOD_USER,
                    UTFALLKODE, BEGRUNNELSE, BRUKERID_ANSVARLIG, AETATENHET_BEHANDLER, AAR, LOPENRSAK, LOPENRVEDTAK,
                    RETTIGHETKODE, AKTFASEKODE, BREV_ID, TOTALBELOP, DATO_MOTTATT, VEDTAK_ID_RELATERT,
                    AVSNITTLISTEKODE_VALGT, PERSON_ID, BRUKERID_BESLUTTER, STATUS_SENSITIV, VEDLEGG_BETPLAN, PARTISJON,
                    OPPSUMMERING_SB2, DATO_UTFORT_DEL1, DATO_UTFORT_DEL2, OVERFORT_NAVI, FRA_DATO, TIL_DATO,
                    SF_OPPFOLGING_ID, STATUS_SOSIALDATA, KONTOR_SOSIALDATA, TEKSTVARIANTKODE, VALGT_BESLUTTER,
                    TEKNISK_VEDTAK, DATO_INNSTILT, ER_UTLAND)
values ('36905537', '13489616', 'IVERK', 'O', to_date('30.08.2022', 'DD.MM.RRRR'), 'KSB0502',
        to_date('30.08.2022', 'DD.MM.RRRR'), 'MNA0502', 'JA', 'Syntetisert rettighet', 'KSB0502', '0502', '2022',
        '73981', '5', 'AAP', 'UGJEN', '31028783', null, to_date('30.08.2022', 'DD.MM.RRRR'), '36905534', null,
        '4873545', 'MNA0502', null, 'N', null, null, null, null, null, to_date('30.08.2022', 'DD.MM.RRRR'),
        to_date('30.08.2023', 'DD.MM.RRRR'), null,
        'N', null, null, 'MNA0502', null, to_date('17.09.2022', 'DD.MM.RRRR'), 'N');


Insert into VEDTAKFAKTA (VEDTAK_ID, VEDTAKFAKTAKODE, VEDTAKVERDI, REG_DATO, REG_USER, MOD_DATO, MOD_USER, PERSON_ID,
                         PARTISJON)
values ('36905537', 'DAGS', '255', to_date('30.08.2022', 'DD.MM.RRRR'), 'KSB0502', to_date('30.08.2022', 'DD.MM.RRRR'),
        'KSB0502', '4873545', null);
