
CREATE TABLE V_DSOP_MELDEKORTDAG_AAP
(
    MELDEKORT_ID    NUMBER      NOT NULL,
    DATO            DATE        NOT NULL,
    TIMER_ARBEIDET  NUMBER      NOT NULL
);

CREATE TABLE V_DSOP_MELDEKORT_AAP
(
    MELDEKORT_ID            NUMBER      NOT NULL,
    FODSELSNR               VARCHAR(11) NOT NULL,
    DATO_FRA                DATE        NOT NULL,
    DATO_TIL                DATE        NOT NULL,
    ANTALL_TIMER_ARBEIDET   NUMBER      NOT NULL
);

CREATE TABLE V_DSOP_VEDTAK_AAP
(
    VEDTAK_ID               NUMBER      NOT NULL,
    FODSELSNR               VARCHAR(11) NOT NULL,
    FRA_DATO                DATE        NOT NULL,
    TIL_DATO                DATE        NOT NULL,
    VEDTAKTYPEKODE          VARCHAR(10),
    VEDTAKTYPENAVN          VARCHAR,
    TEKSTVARIANTKODE        VARCHAR(10),
    TEKSTVARIANTNAVN        VARCHAR,
    VEDTAKSTATUSKODE        VARCHAR(10),
    VEDTAKSTATUSNAVN        VARCHAR,
    RETTIGHETKODE           VARCHAR(10),
    RETTIGHETNAVN           VARCHAR,
    UTFALLKODE              VARCHAR(10),
    UTFALLNAVN              VARCHAR,
    AKTFASEKODE             VARCHAR(10),
    AKTFASENAVN             VARCHAR
);


INSERT INTO V_DSOP_MELDEKORTDAG_AAP (MELDEKORT_ID, DATO, TIMER_ARBEIDET)
VALUES (1, to_date('09.10.2023', 'DD.MM.RRRR'), 0.0);

INSERT INTO V_DSOP_MELDEKORTDAG_AAP (MELDEKORT_ID, DATO, TIMER_ARBEIDET)
VALUES (1, to_date('10.10.2023', 'DD.MM.RRRR'), 7.5);

INSERT INTO V_DSOP_MELDEKORTDAG_AAP (MELDEKORT_ID, DATO, TIMER_ARBEIDET)
VALUES (1, to_date('11.10.2023', 'DD.MM.RRRR'), 2.0);

INSERT INTO V_DSOP_MELDEKORTDAG_AAP (MELDEKORT_ID, DATO, TIMER_ARBEIDET)
VALUES (1, to_date('12.10.2023', 'DD.MM.RRRR'), 0.0);

INSERT INTO V_DSOP_MELDEKORTDAG_AAP (MELDEKORT_ID, DATO, TIMER_ARBEIDET)
VALUES (1, to_date('13.10.2023', 'DD.MM.RRRR'), 0.0);

INSERT INTO V_DSOP_MELDEKORTDAG_AAP (MELDEKORT_ID, DATO, TIMER_ARBEIDET)
VALUES (1, to_date('16.10.2023', 'DD.MM.RRRR'), 0.0);

INSERT INTO V_DSOP_MELDEKORTDAG_AAP (MELDEKORT_ID, DATO, TIMER_ARBEIDET)
VALUES (1, to_date('17.10.2023', 'DD.MM.RRRR'), 5.0);

INSERT INTO V_DSOP_MELDEKORTDAG_AAP (MELDEKORT_ID, DATO, TIMER_ARBEIDET)
VALUES (1, to_date('18.10.2023', 'DD.MM.RRRR'), 0.0);

INSERT INTO V_DSOP_MELDEKORTDAG_AAP (MELDEKORT_ID, DATO, TIMER_ARBEIDET)
VALUES (1, to_date('19.10.2023', 'DD.MM.RRRR'), 0.0);

INSERT INTO V_DSOP_MELDEKORTDAG_AAP (MELDEKORT_ID, DATO, TIMER_ARBEIDET)
VALUES (1, to_date('20.10.2023', 'DD.MM.RRRR'), 7.5);

INSERT INTO V_DSOP_MELDEKORT_AAP (MELDEKORT_ID, FODSELSNR, DATO_FRA, DATO_TIL, ANTALL_TIMER_ARBEIDET)
VALUES (1, '12345678910', to_date('09.10.2023', 'DD.MM.RRRR'), to_date('20.10.2023', 'DD.MM.RRRR'), 22.0);

INSERT INTO V_DSOP_VEDTAK_AAP (VEDTAK_ID, FODSELSNR, FRA_DATO, TIL_DATO, VEDTAKTYPEKODE, VEDTAKTYPENAVN,
                               TEKSTVARIANTKODE, TEKSTVARIANTNAVN, VEDTAKSTATUSKODE, VEDTAKSTATUSNAVN,
                               RETTIGHETKODE, RETTIGHETNAVN, UTFALLKODE, UTFALLNAVN, AKTFASEKODE, AKTFASENAVN)
VALUES (1, '12345678910', to_date('01.01.2023', 'DD.MM.RRRR'), to_date('31.10.2023', 'DD.MM.RRRR'),
        'O', 'Vanlig', 'T', 'Tekst', 'I', 'Innvilget', 'AAP', 'AAP', 'S', 'Stans', 'O', 'Vanlig');
