@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
title Systemer under migreringen

System_Boundary(arena, "Arena <FSS>") {
    ContainerDb(arena_db, "Database", "Oracle 19")
    Container(aap_tilgangsview, "AAP tilgangsview", "View")
    Container(saksbehandling_arena, "Saksbehandling", "Component")
            note left of saksbehandling_arena : Endre
    Container(arena_ws_api, "Arena WS-API")

    Rel(aap_tilgangsview, arena_db, "videresender")
    Rel(arena_ws_api, arena_db, "spørringer")
    Rel(saksbehandling_arena, arena_db, "spørringer")

}

System_Boundary(kelvin, "Kelvin <GCP>") {

    Container(postmottak, "postmottak", "Fordeler innkommende søknader")
        note left of postmottak : Adopter

    Container(saksbehandling_kelvin, "saksbehandling", "Frontend for saksbehandling")
        note left of saksbehandling_kelvin : Endre
    Container(behandlingsflyt, "Behandlingsflyt", "Backend for saksbehandling")
        note right of behandlingsflyt : Endre

    Container(api_intern, "api-intern", "API")
    Container(api_ekstern, "api-ekstern", "API for eksterne")

    ContainerDb(kelvin_db, "Database", "Postgres")

    Rel(api_ekstern, api_intern, "videresender")
    Rel(behandlingsflyt, kelvin_db, "spørringer")
    Rel(saksbehandling_kelvin, behandlingsflyt, "saksbehandling")
}

System_Boundary(kelvin_fss, "Kelvin <FSS>") {
    Container(aap_fss_proxy, "fss-proxy", "REST-proxy mot Arena-WS")
            note left of aap_fss_proxy : Adopter
    Container(arena_oppslag, "Arena-oppslag", "Database-klient")
        note left of arena_oppslag : Adopter

    Container(migrering, "Migrerings-motor", "Konverterer åpne Arena-saker")
        note left of migrering : Ny

    Rel(arena_oppslag, aap_tilgangsview, "spørringer")

    Rel(api_intern, arena_oppslag, "api-kall")
    Rel(postmottak, aap_fss_proxy, "opprett sak")
    Rel(postmottak, behandlingsflyt, "opprett sak")


    Rel(aap_fss_proxy, arena_ws_api, "api-kall")
    Rel(migrering, arena_oppslag, "api-kall")
    Rel(behandlingsflyt, arena_oppslag, "api-kall")
    Rel(migrering, api_intern, "api-kall")
}

System(joark, "Joark")
System(altinn, "Altinn")
System(pensjonkasser, "Pensjonskasser", "pensjonsamhandling")
Rel(pensjonkasser, api_ekstern, "oppslag")
Rel(joark, postmottak, "AAP-søknader")
Rel(altinn, api_ekstern, "oppslag")

System(visningsklient, "Visningsklient", "AAP-saker i Arena")
note right of visningsklient : Ny
Rel(visningsklient, arena_oppslag, "saksinformasjon")

Person(saksbehandler, "Saksbehandler", "NAV-ansatt")

Rel(saksbehandler, saksbehandling_kelvin, "Bruker")
Rel(saksbehandler, saksbehandling_arena, "Bruker")
Rel(saksbehandler, visningsklient, "Bruker")

@enduml
