-- Testdata for saksopplysninger knyttet til vedtak 37067849 (person 12312312312)
-- SAK_ID 13489616 er saken vedtaket tilhører (fra V1_3__arena_data.sql)

Insert into SAKSOPPLYSNINGTYPE (SAKSOPPLYSNINGKODE, SAKSOPPLYSNINGNAVN, SKJERMBILDETEKST, STATUS_REPETERBAR)
values ('ARBEVNE', 'Arbeidsevne', 'Vurdering av arbeidsevne', 'N');

Insert into SAKSOPPLYSNING (SAKSOPPLYSNING_ID, SAK_ID, SAKSOPPLYSNINGKODE, VERDI)
values (1001, 13489616, 'ARBEVNE', 'NEI');

Insert into ATTRIBUTTYPE (ATTRIBUTTYPE_ID, SAKSOPPLYSNINGKODE, ATTRIBUTTKODE, SKJERMBILDETEKST, FORMATNAVN, POSISJON)
values (2001, 'ARBEVNE', 'BEGRUNNELSE', 'Begrunnelse', 'TEKST', 1);

Insert into ATTRIBUTTYPE (ATTRIBUTTYPE_ID, SAKSOPPLYSNINGKODE, ATTRIBUTTKODE, SKJERMBILDETEKST, FORMATNAVN, POSISJON)
values (2002, 'ARBEVNE', 'DATO', 'Dato vurdert', 'DATO', 2);

Insert into ATTRIBUTT (ATTRIBUTT_ID, SAKSOPPLYSNING_ID_EIER, ATTRIBUTTYPE_ID, VERDI, STATUS_SJEKKET_AV)
values (3001, 1001, 2001, 'Bruker kan ikke jobbe', 'A');

Insert into ATTRIBUTT (ATTRIBUTT_ID, SAKSOPPLYSNING_ID_EIER, ATTRIBUTTYPE_ID, VERDI, STATUS_SJEKKET_AV)
values (3002, 1001, 2002, '2022-08-30', null);

Insert into LOV_VEDTAK_SAKSOPPLYSNING (VEDTAK_ID, SAKSOPPLYSNING_ID)
values (37067849, 1001);
