
CREATE TABLE V_DSOP_MELDEKORTDAG_AAP
(
    MELDEKORT_ID    NUMBER      NOT NULL,
    DATO            DATE        NOT NULL,
    TIMER_ARBEIDET  NUMBER      NOT NULL
);

CREATE TABLE V_DSOP_MELDEKORT_AAP
(
    MELDEKORT_ID            NUMBER      NOT NULL,
    FODSELSNR               VARCHAR(11) NOT NULL,
    DATO_FRA                DATE        NOT NULL,
    DATO_TIL                DATE        NOT NULL,
    ANTALL_TIMER_ARBEIDET   NUMBER      NOT NULL
);

CREATE TABLE V_DSOP_VEDTAK_AAP
(
    VEDTAK_ID               NUMBER      NOT NULL,
    FODSELSNR               VARCHAR(11) NOT NULL,
    FRA_DATO                DATE        NOT NULL,
    TIL_DATO                DATE        NOT NULL,
    VEDTAKTYPEKODE          VARCHAR(10),
    VEDTAKTYPENAVN          VARCHAR,
    TEKSTVARIANTKODE        VARCHAR(10),
    TEKSTVARIANTNAVN        VARCHAR,
    VEDTAKSTATUSKODE        VARCHAR(10),
    VEDTAKSTATUSNAVN        VARCHAR,
    RETTIGHETKODE           VARCHAR(10),
    RETTIGHETNAVN           VARCHAR,
    UTFALLKODE              VARCHAR(10),
    UTFALLNAVN              VARCHAR,
    AKTFASEKODE             VARCHAR(10),
    AKTFASENAVN             VARCHAR
);


INSERT INTO V_DSOP_MELDEKORTDAG_AAP (MELDEKORT_ID, DATO, TIMER_ARBEIDET)
VALUES (1, DATE '2023-10-09', 0.0);

INSERT INTO V_DSOP_MELDEKORTDAG_AAP (MELDEKORT_ID, DATO, TIMER_ARBEIDET)
VALUES (1, DATE '2023-10-10', 7.5);

INSERT INTO V_DSOP_MELDEKORTDAG_AAP (MELDEKORT_ID, DATO, TIMER_ARBEIDET)
VALUES (1, DATE '2023-10-11', 2.0);

INSERT INTO V_DSOP_MELDEKORTDAG_AAP (MELDEKORT_ID, DATO, TIMER_ARBEIDET)
VALUES (1, DATE '2023-10-12', 0.0);

INSERT INTO V_DSOP_MELDEKORTDAG_AAP (MELDEKORT_ID, DATO, TIMER_ARBEIDET)
VALUES (1, DATE '2023-10-13', 0.0);

INSERT INTO V_DSOP_MELDEKORTDAG_AAP (MELDEKORT_ID, DATO, TIMER_ARBEIDET)
VALUES (1, DATE '2023-10-16', 0.0);

INSERT INTO V_DSOP_MELDEKORTDAG_AAP (MELDEKORT_ID, DATO, TIMER_ARBEIDET)
VALUES (1, DATE '2023-10-17', 5.0);

INSERT INTO V_DSOP_MELDEKORTDAG_AAP (MELDEKORT_ID, DATO, TIMER_ARBEIDET)
VALUES (1, DATE '2023-10-18', 0.0);

INSERT INTO V_DSOP_MELDEKORTDAG_AAP (MELDEKORT_ID, DATO, TIMER_ARBEIDET)
VALUES (1, DATE '2023-10-19', 0.0);

INSERT INTO V_DSOP_MELDEKORTDAG_AAP (MELDEKORT_ID, DATO, TIMER_ARBEIDET)
VALUES (1, DATE '2023-10-20', 7.5);

INSERT INTO V_DSOP_MELDEKORT_AAP (MELDEKORT_ID, FODSELSNR, DATO_FRA, DATO_TIL, ANTALL_TIMER_ARBEIDET)
VALUES (1, '12345678910', DATE '2023-10-09', DATE '2023-10-20', 22.0);

INSERT INTO V_DSOP_VEDTAK_AAP (VEDTAK_ID, FODSELSNR, FRA_DATO, TIL_DATO, VEDTAKTYPEKODE, VEDTAKTYPENAVN,
                               TEKSTVARIANTKODE, TEKSTVARIANTNAVN, VEDTAKSTATUSKODE, VEDTAKSTATUSNAVN,
                               RETTIGHETKODE, RETTIGHETNAVN, UTFALLKODE, UTFALLNAVN, AKTFASEKODE, AKTFASENAVN)
VALUES (1, '12345678910', DATE '2023-01-01', DATE '2023-10-31',
        'O', 'Vanlig', 'T', 'Tekst', 'I', 'Innvilget', 'AAP', 'AAP', 'S', 'Stans', 'O', 'Vanlig');
